"""
Classical ML anomaly classifier — XGBoost + Random Forest on hand-crafted features.

Pipeline:
  1. Load pre-extracted feature vectors from data/processed/{clip_id}_features.npz
     (generated by scripts/build_features.py)
  2. Load human labels from the DB (Label table, populated via admin labeling UI)
  3. Train XGBoost binary classifier with stratified 5-fold cross-validation
  4. Train Random Forest as a comparison model
  5. Report F1, precision, recall, AUC-ROC for both models
  6. Save the best model (by validation F1) to models/classical_xgb.pkl

Feature vector (19 features, all float32 — see scripts/build_features.py):
  flow_mean, flow_std, flow_max, flow_p75, flow_p90, flow_p95,
  window_max_mean, window_max_peak, window_max_std, window_n_flagged,
  direction_variance, direction_change_rate,
  blur_mean, blur_min,
  edge_density_std, edge_density_max_change,
  n_magnitude_spikes, spike_rate, max_consecutive_spikes

Design notes:
  - XGBoost handles class imbalance via scale_pos_weight
  - Features are StandardScaler-normalized before RF (not needed for XGBoost
    but included so the scaler is always saved alongside the model)
  - SMOTE oversampling applied if anomaly class < 20% of training set
  - Feature importances logged and saved for interpretability
"""

import json
import logging
import pickle
from dataclasses import dataclass, field
from pathlib import Path

import numpy as np

logger = logging.getLogger(__name__)

MODEL_PATH = Path("models/classical_xgb.pkl")
RF_MODEL_PATH = Path("models/classical_rf.pkl")
EVAL_OUTPUT_PATH = Path("data/outputs/classical_eval.json")


@dataclass
class ClassicalResult:
    """Inference result from the classical ML classifier."""
    clip_id: str
    is_anomaly: bool
    anomaly_probability: float          # 0.0 – 1.0
    feature_importances: dict[str, float] = field(default_factory=dict)
    # Per-clip standardised feature values (z-scores vs the training
    # distribution). The most-positive z-score identifies which feature
    # makes *this* clip look abnormal — used downstream to pick a
    # per-clip anomaly type rather than a global constant.
    feature_zscores: dict[str, float] = field(default_factory=dict)


class ClassicalAnomalyClassifier:
    """
    XGBoost-based anomaly classifier trained on hand-crafted clip features.

    Wraps an XGBoost binary classifier and a fitted StandardScaler.
    Both are serialised together to a single .pkl file so loading is a
    single call with no external state.
    """

    def __init__(self, model_path: str | Path = MODEL_PATH) -> None:
        self.model_path = Path(model_path)
        self._model = None          # xgboost.XGBClassifier
        self._scaler = None         # sklearn.preprocessing.StandardScaler
        self._feature_names: list[str] = []

    # ── Training ──────────────────────────────────────────────────────────────

    def train(
        self,
        features_dir: str | Path = "data/processed",
        n_folds: int = 5,
        random_state: int = 42,
    ) -> dict[str, float]:
        """
        Train the XGBoost classifier on labeled clip features.

        Loads feature vectors and labels from disk/DB, applies SMOTE if the
        dataset is imbalanced, trains with stratified k-fold CV, and saves
        both XGBoost and Random Forest models to models/.

        Args:
            features_dir: Directory containing .npz feature files.
            n_folds: Number of stratified cross-validation folds.
            random_state: Random seed for reproducibility.

        Returns:
            Dict of evaluation metrics across all folds:
            {xgb_f1, xgb_auc, rf_f1, rf_auc, precision, recall, n_samples}
        """
        import xgboost as xgb
        from sklearn.ensemble import RandomForestClassifier
        from sklearn.model_selection import StratifiedKFold, cross_validate
        from sklearn.preprocessing import StandardScaler
        from sklearn.metrics import f1_score, roc_auc_score
        from scripts.build_features import feature_names, load_features

        X, y, clip_ids = self._load_dataset(features_dir)
        if X is None:
            raise RuntimeError("No labeled feature data found. Run build_features.py first.")

        self._feature_names = feature_names()
        n_pos = int(np.sum(y))
        n_neg = len(y) - n_pos
        logger.info("Dataset: %d clips (%d anomaly, %d normal)", len(y), n_pos, n_neg)

        # Apply SMOTE if minority class < 20%
        if n_pos / len(y) < 0.20:
            logger.info("Applying SMOTE (anomaly rate=%.1f%%)", 100 * n_pos / len(y))
            try:
                from imblearn.over_sampling import SMOTE
                X, y = SMOTE(random_state=random_state).fit_resample(X, y)
                logger.info("After SMOTE: %d samples", len(y))
            except ImportError:
                logger.warning("imbalanced-learn not installed, skipping SMOTE")

        scaler = StandardScaler()
        X_scaled = scaler.fit_transform(X)

        scale_pos_weight = n_neg / max(n_pos, 1)
        xgb_clf = xgb.XGBClassifier(
            n_estimators=300,
            max_depth=6,
            learning_rate=0.05,
            subsample=0.8,
            colsample_bytree=0.8,
            scale_pos_weight=scale_pos_weight,
            use_label_encoder=False,
            eval_metric="logloss",
            random_state=random_state,
            n_jobs=-1,
        )

        rf_clf = RandomForestClassifier(
            n_estimators=300,
            max_depth=8,
            class_weight="balanced",
            random_state=random_state,
            n_jobs=-1,
        )

        cv = StratifiedKFold(n_splits=n_folds, shuffle=True, random_state=random_state)
        scoring = ["f1", "roc_auc", "precision", "recall"]

        logger.info("Running %d-fold CV for XGBoost...", n_folds)
        xgb_scores = cross_validate(xgb_clf, X_scaled, y, cv=cv, scoring=scoring)

        logger.info("Running %d-fold CV for Random Forest...", n_folds)
        rf_scores = cross_validate(rf_clf, X_scaled, y, cv=cv, scoring=scoring)

        # Refit on full dataset for saving
        xgb_clf.fit(X_scaled, y)
        rf_clf.fit(X_scaled, y)

        self._model = xgb_clf
        self._scaler = scaler

        metrics = {
            "xgb_f1":         float(np.mean(xgb_scores["test_f1"])),
            "xgb_auc":        float(np.mean(xgb_scores["test_roc_auc"])),
            "xgb_precision":  float(np.mean(xgb_scores["test_precision"])),
            "xgb_recall":     float(np.mean(xgb_scores["test_recall"])),
            "rf_f1":          float(np.mean(rf_scores["test_f1"])),
            "rf_auc":         float(np.mean(rf_scores["test_roc_auc"])),
            "n_samples":      len(y),
            "n_positive":     int(np.sum(y)),
            "n_folds":        n_folds,
        }

        # Log feature importances
        importances = dict(zip(self._feature_names, xgb_clf.feature_importances_))
        top = sorted(importances.items(), key=lambda x: x[1], reverse=True)[:5]
        logger.info("Top XGBoost features: %s", top)

        self.save()
        self._save_rf(rf_clf, scaler)
        self._save_eval(metrics, importances)

        return metrics

    # ── Inference ─────────────────────────────────────────────────────────────

    def predict(
        self,
        clip_id: str,
        features_dir: str | Path = "data/processed",
    ) -> ClassicalResult:
        """
        Run inference on a single clip using its pre-extracted features.

        Args:
            clip_id: UUID string of the clip.
            features_dir: Directory containing .npz files.

        Returns:
            ClassicalResult with anomaly probability and feature importances.

        Raises:
            FileNotFoundError: If the feature file for clip_id does not exist.
            RuntimeError: If the model has not been loaded or trained.
        """
        from scripts.build_features import load_features, feature_names

        if self._model is None:
            self.load()

        features = load_features(clip_id, Path(features_dir))
        if features is None:
            raise FileNotFoundError(
                f"No feature file found for clip {clip_id}. Run build_features.py first."
            )

        X = self._scaler.transform(features.reshape(1, -1))
        prob = float(self._model.predict_proba(X)[0, 1])
        is_anomaly = prob >= 0.5

        names = feature_names()
        importances = {}
        if hasattr(self._model, "feature_importances_"):
            importances = dict(zip(names, self._model.feature_importances_.tolist()))

        # X is already standardised by StandardScaler, so each entry IS a
        # z-score of that feature vs the training population. The most
        # positive entry indicates which feature is most anomalous for
        # this specific clip.
        zscores = dict(zip(names, X[0].tolist()))

        return ClassicalResult(
            clip_id=clip_id,
            is_anomaly=is_anomaly,
            anomaly_probability=prob,
            feature_importances=importances,
            feature_zscores=zscores,
        )

    def predict_batch(
        self,
        clip_ids: list[str],
        features_dir: str | Path = "data/processed",
    ) -> list[ClassicalResult]:
        """Run inference on multiple clips."""
        return [self.predict(cid, features_dir) for cid in clip_ids]

    # ── Persistence ───────────────────────────────────────────────────────────

    def save(self) -> None:
        """Persist the XGBoost model and scaler to disk."""
        if self._model is None:
            raise RuntimeError("No model to save — train first.")
        self.model_path.parent.mkdir(parents=True, exist_ok=True)
        with open(self.model_path, "wb") as f:
            pickle.dump({"model": self._model, "scaler": self._scaler,
                         "feature_names": self._feature_names}, f)
        logger.info("Saved XGBoost model to %s", self.model_path)

    def load(self) -> None:
        """Load XGBoost model and scaler from disk."""
        if not self.model_path.exists():
            raise FileNotFoundError(f"No model file at {self.model_path}. Train first.")
        with open(self.model_path, "rb") as f:
            data = pickle.load(f)
        self._model = data["model"]
        self._scaler = data["scaler"]
        self._feature_names = data.get("feature_names", [])
        logger.info("Loaded XGBoost model from %s", self.model_path)

    # ── Private helpers ───────────────────────────────────────────────────────

    def _load_dataset(
        self, features_dir: str | Path
    ) -> tuple[np.ndarray | None, np.ndarray | None, list[str]]:
        """
        Load feature matrix X and label vector y from DB + disk.

        Joins labeled clips from the DB with their .npz feature files.
        Clips that have a label but no feature file are skipped with a warning.

        Returns:
            (X array shape (n, 19), y array shape (n,), clip_id list)
            Returns (None, None, []) if no data is available.
        """
        from api.database import SessionLocal
        from api.models.db_models import Clip, Label
        from scripts.build_features import load_features

        features_dir = Path(features_dir)
        db = SessionLocal()
        rows: list[tuple[np.ndarray, int, str]] = []

        try:
            labeled = db.query(Clip, Label).join(Label, Clip.id == Label.clip_id).all()
            if not labeled:
                return None, None, []

            for clip, label in labeled:
                vec = load_features(str(clip.id), features_dir)
                if vec is None:
                    logger.warning("No features for %s — skipping", clip.filename_prefix)
                    continue
                rows.append((vec, int(label.is_anomaly), str(clip.id)))
        finally:
            db.close()

        if not rows:
            return None, None, []

        X = np.stack([r[0] for r in rows])
        y = np.array([r[1] for r in rows], dtype=np.int32)
        ids = [r[2] for r in rows]
        return X, y, ids

    def _save_rf(self, rf_model, scaler) -> None:
        """Save the Random Forest comparison model."""
        RF_MODEL_PATH.parent.mkdir(parents=True, exist_ok=True)
        with open(RF_MODEL_PATH, "wb") as f:
            pickle.dump({"model": rf_model, "scaler": scaler,
                         "feature_names": self._feature_names}, f)
        logger.info("Saved Random Forest model to %s", RF_MODEL_PATH)

    def _save_eval(self, metrics: dict, importances: dict) -> None:
        """Write evaluation metrics and feature importances to JSON."""
        EVAL_OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
        output = {"metrics": metrics, "feature_importances": importances}
        EVAL_OUTPUT_PATH.write_text(json.dumps(output, indent=2, default=lambda o: float(o) if hasattr(o, 'item') else str(o)))
        logger.info("Saved evaluation results to %s", EVAL_OUTPUT_PATH)
