"""initial_schema

Revision ID: 1443b1d66915
Revises:
Create Date: 2026-04-10 17:16:11.200942

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1443b1d66915"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clips",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("r2_key_front", sa.String(length=512), nullable=False),
        sa.Column("r2_key_rear", sa.String(length=512), nullable=False),
        sa.Column("filename_prefix", sa.String(length=256), nullable=False),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column("file_size_bytes_front", sa.Integer(), nullable=True),
        sa.Column("file_size_bytes_rear", sa.Integer(), nullable=True),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "processing_status",
            sa.Enum("PENDING", "PROCESSING", "DONE", "FAILED", name="processingstatus"),
            nullable=False,
        ),
        sa.Column("processing_error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_clips_filename_prefix"), "clips", ["filename_prefix"], unique=False
    )
    op.create_index(
        op.f("ix_clips_processing_status"), "clips", ["processing_status"], unique=False
    )
    op.create_table(
        "overall_driver_scores",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "model_type",
            sa.Enum("BASELINE", "CLASSICAL", "DEEP_LEARNING", name="modeltype"),
            nullable=False,
        ),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("grade", sa.String(length=1), nullable=False),
        sa.Column("clips_analyzed", sa.Integer(), nullable=False),
        sa.Column("breakdown", sa.JSON(), nullable=True),
        sa.Column(
            "calculated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "anomalies",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("clip_id", sa.UUID(), nullable=False),
        sa.Column(
            "model_type",
            sa.Enum("BASELINE", "CLASSICAL", "DEEP_LEARNING", name="modeltype"),
            nullable=False,
        ),
        sa.Column(
            "anomaly_type",
            sa.Enum(
                "HARD_BRAKING",
                "HARD_ACCELERATION",
                "NEAR_MISS",
                "LANE_DEPARTURE",
                "TRAFFIC_VIOLATION",
                "TAILGATING",
                "AGGRESSIVE_LANE_CHANGE",
                "HARSH_CORNERING",
                "DISTRACTED_DRIVING",
                "OTHER",
                name="anomalytype",
            ),
            nullable=False,
        ),
        sa.Column("severity", sa.Float(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("timestamp_start", sa.Float(), nullable=False),
        sa.Column("timestamp_end", sa.Float(), nullable=False),
        sa.Column("score_impact", sa.Float(), nullable=False),
        sa.Column("detection_metadata", sa.JSON(), nullable=True),
        sa.Column("ai_explanation", sa.Text(), nullable=True),
        sa.Column(
            "detected_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["clip_id"], ["clips.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_anomalies_anomaly_type"), "anomalies", ["anomaly_type"], unique=False
    )
    op.create_index(
        op.f("ix_anomalies_clip_id"), "anomalies", ["clip_id"], unique=False
    )
    op.create_index(
        op.f("ix_anomalies_model_type"), "anomalies", ["model_type"], unique=False
    )
    op.create_table(
        "labels",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("clip_id", sa.UUID(), nullable=False),
        sa.Column("is_anomaly", sa.Boolean(), nullable=False),
        sa.Column("anomaly_types", sa.JSON(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column(
            "labeled_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["clip_id"], ["clips.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_labels_clip_id"), "labels", ["clip_id"], unique=True)
    op.create_table(
        "scores",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("clip_id", sa.UUID(), nullable=False),
        sa.Column(
            "model_type",
            sa.Enum("BASELINE", "CLASSICAL", "DEEP_LEARNING", name="modeltype"),
            nullable=False,
        ),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("grade", sa.String(length=1), nullable=False),
        sa.Column("anomaly_count", sa.Integer(), nullable=False),
        sa.Column(
            "calculated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["clip_id"], ["clips.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_scores_clip_id"), "scores", ["clip_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_scores_clip_id"), table_name="scores")
    op.drop_table("scores")
    op.drop_index(op.f("ix_labels_clip_id"), table_name="labels")
    op.drop_table("labels")
    op.drop_index(op.f("ix_anomalies_model_type"), table_name="anomalies")
    op.drop_index(op.f("ix_anomalies_clip_id"), table_name="anomalies")
    op.drop_index(op.f("ix_anomalies_anomaly_type"), table_name="anomalies")
    op.drop_table("anomalies")
    op.drop_table("overall_driver_scores")
    op.drop_index(op.f("ix_clips_processing_status"), table_name="clips")
    op.drop_index(op.f("ix_clips_filename_prefix"), table_name="clips")
    op.drop_table("clips")
    # ### end Alembic commands ###
